name: 'Handlebars action'
description: 'Compiles and renders payloads from Handlebar templates.'
author: 'Tyler Garner'
inputs:
  template:
    required: true
    description: Handlebar template to use.
outputs:
    payload: ${{ steps.compile.outputs.payload }}
runs:
  using: 'node16'
  main: 'main.js'
    