name: 'say hello'
on: # rebuild any PRs and main branch changes
  workflow_dispatch:
jobs:
  check-perms:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          token: ${{ secrets.TOKEN }}
          template: Sup {{ name }}?
          name: tyler