name: 'Create Docs'
on:
  workflow_dispatch:
jobs:
  check-perms:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
      - name: install dependencies
        run: |
          npm install
      - uses: octokit/request-action@v2.x
        id: open-pull-requests
        with:
          route: /repos/:owner/:repo/pulls
          owner: garnertb
          repo: handlebar-action
      - uses: ./
        with:
          prs: ${{ steps.open-pull-requests.outputs.data }}
          description: ''
          template: |- 
            ## Weekly Sync {{ date}}
            
            <!-- Items actively working or blocked -->
            ### In Progress

            ### PRs Needing Review
            {{ #each prs }}
              - [{{ pr.title }}]({{ pr.html_url }})
            {{ /each }}
            ### Security
            <!-- Security-related Issues/PRS -->

            ### Expenses
            <!-- Image from AWS Cost Explorer -->

            ### Deployments
            