name: 'Create Issue'
on:
  workflow_dispatch:
jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
      - name: install dependencies
        run: |
          npm install
      - uses: octokit/request-action@v2.x
        id: open-issues
        with:
          route: /repos/:owner/:repo/issues?sort=updated&per_page=100&state=all
          owner: garnertb
          repo: handlebars-action
        env:
          GITHUB_TOKEN: ${{ secrets.token }} 
      - uses: ./
        id: issue-body
        with:
          issues: ${{ steps.open-issues.outputs.data }}
          template: |
            ## Open issues
            {{#each issues }}
            {{#withinAWeek this.updated_at}}
            - [ ] #{{this.number}}
            {{/withinAWeek}}
            {{/each }}
      - uses: imjohnbo/issue-bot@v3
        with:
          body: ${{ steps.issue-body.outputs.payload }}
          title: Issues from this week

          