name: Say Hello
on:
  workflow_dispatch:
jobs:
  check-perms:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: install dependencies
        run: |
          npm install
      - uses: ./
        with:
          template: Whats up {{ name }}?
          name: Mona